---
- name: Déployer sur l'environnement de production
  hosts: prod
  become: yes

  tasks:
    - name: Arrêter l'ancienne version de l'application
      command: systemctl stop mon_application_prod

    - name: Récupérer la dernière version depuis Git
      git:
        repo: "lien_vers_le_repo_git"
        dest: "/chemin/vers/application"
        version: master
        force: yes

    - name: Construire et déployer l'application
      command: "grails clean && grails compile && grails run-app &"
